# Copyright 2015-2026 Earth Sciences Department, BSC-CNS
#
# This file is part of Autosubmit.
#
# Autosubmit is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Autosubmit is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Autosubmit.  If not, see <http://www.gnu.org/licenses/>.

"""catlog

Displays logs from the command line.

It is possible to use ``autosubmit cat-log`` for Workflow and for Job logs. It decides
whether to show Workflow or Job logs based on the ``ID`` given. Shorter ID's, such as
``a000`` are considered Workflow ID's, so it will display logs for that workflow. For
longer ID's, such as ``a000_20220401_fc0_1_GSV``, the command will display logs for
that specific job.

Users can choose the log file using the ``FILE`` parameter, to display an error or
output log file, for instance.

Finally, the ``MODE`` parameter allows users to choose whether to display the complete
file contents (similar to the ``cat`` command) or to start tailing its output (akin to
``tail -f``).

Examples:

    # Show the output logs of a workflow.
    $ autosubmit catlog a000

    # Show the logs of a specific job.
    $ autosubmit catlog a000_20220401_fc0_1_GSV

    # Show the error log of a workflow.
    $ autosubmit catlog --file e a000

    # Follow the output log as it grows.
    $ autosubmit catlog --mode t a000
"""

from argparse import ArgumentParser

from autosubmit.log.catlog import cat_log
from autosubmit.scripts._args import (
    ExpidOptions,
    create_argparse_parser,
)
from autosubmit.scripts._cli_function import cli_function
from autosubmit.scripts._validation import validate_expid


class CatlogOptions(ExpidOptions):
    """Options for the catlog command."""

    file: str
    mode: str
    inspect: bool
    ID: str


def args_parser() -> ArgumentParser:
    parser = create_argparse_parser(__doc__)

    parser.add_argument(
        "-f",
        "--file",
        default=None,
        action="store",
        metavar="FILE",
        help="Workflow or Job log file. Options are o(output), j(job), e(error), s(status). Default o(output).",
    )
    parser.add_argument(
        "-m",
        "--mode",
        default=None,
        action="store",
        metavar="MODE",
        help="Mode. Options are c(cat), t(tail). Default is c(cat).",
    )
    parser.add_argument(
        "-i",
        "--inspect",
        default=False,
        action="store_true",
        help="Read job files generated by the inspect subcommand.",
    )
    parser.add_argument(
        "ID",
        metavar="ID",
        help="An ID of a Workflow (eg a000) or a Job (eg a000_20220401_fc0_1_1_APPLICATION).",
    )

    return parser


@cli_function(
    args_parser=args_parser, options_type=CatlogOptions, validators=validate_expid
)
def main(opts: CatlogOptions) -> int | bool | None:
    return cat_log(opts.ID, opts.file, opts.mode, opts.inspect)
