# Copyright 2015-2026 Earth Sciences Department, BSC-CNS
#
# This file is part of Autosubmit.
#
# Autosubmit is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Autosubmit is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Autosubmit.  If not, see <http://www.gnu.org/licenses/>.

"""report

Generates a report of the variables available to jobs in an experiment.

The report is generated by parsing the experiment configuration and can
be used by workflow developers to inspect the parameters available when
writing job templates and shell scripts.

Examples:
    # Generate a report for an experiment
    $ autosubmit report a000

    # Generate a report using a specific metric template
    $ autosubmit report a000 --template my_template

    # Generate a file containing all available parameters
    $ autosubmit report a000 --show_all_parameters

    # Generate the report in a specific folder
    $ autosubmit report a000 --folder_path /path/to/reports

    # Keep placeholders instead of substituting them
    $ autosubmit report a000 --placeholders
"""

from argparse import ArgumentParser

from autosubmit.experiment.manage import report
from autosubmit.scripts._args import (
    ExpidOptions,
    create_argparse_parser,
)
from autosubmit.scripts._cli_function import cli_function
from autosubmit.scripts._validation import validate_expid


class ReportOptions(ExpidOptions):
    """Options for the report command."""

    template: str
    show_all_parameters: bool
    folder_path: str
    placeholders: bool


def args_parser() -> ArgumentParser:
    parser = create_argparse_parser(__doc__)

    parser.add_argument(
        "-t", "--template", type=str, help="Supply the metric template."
    )
    parser.add_argument(
        "-all",
        "--show_all_parameters",
        action="store_true",
        default=False,
        help="Writes a file containing all parameters",
    )
    parser.add_argument(
        "-fp", "--folder_path", type=str, help="Allows to select a non-default folder."
    )
    parser.add_argument(
        "-p",
        "--placeholders",
        default=False,
        action="store_true",
        help="disables the substitution of placeholders by -",
    )

    return parser


@cli_function(
    args_parser=args_parser, options_type=ReportOptions, validators=validate_expid
)
def main(opts: ReportOptions) -> int | bool | None:
    return report(
        opts.expid,
        opts.template,
        opts.show_all_parameters,
        opts.folder_path,
        opts.placeholders,
    )
