test:
  cache:
    paths:
      - ~/venv/autosubmit
  script:
  - source ~/venv/autosubmit/bin/activate
  - nosetests test --ignore-files="test_job_graph.py" --with-coverage --cover-xml
  - python-codacy-coverage -r test/coverage.xml