# If you modify this file, please validate it before committing:
# curl --data-binary @codecov.yml https://codecov.io/validate
#
# Quick-start: https://docs.codecov.com/docs/quick-start

codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "75...100"

  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

ignore:
  - "test"
  - "autosubmit/job/template/common.py"

flag_management:
  default_rules:
    carryforward: true

comment:
  layout: " diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  hide_project_coverage: false
