name: autosubmit
channels:
- conda-forge

dependencies:
- nose
- paramiko
- pydotplus
- python-dateutil
- pyparsing
- numpy
- matplotlib

- mock
- portalocker
- networkx

- pip:
  - bscearth.utils
  - saga-python

