name: autosubmit
channels:
- conda-forge

dependencies:
- nose
- paramiko
- pydotplus
- python-dateutil
- pyparsing
- numpy
- matplotlib
- saga-python
- mock
- portalocker
- networkx

- pip:
  - bscearth.utils

