name: autosubmit
channels:
- conda-forge

dependencies:
- nose
- nose-cov
- paramiko
- pydotplus
- python-dateutil
- pyparsing
- numpy
- matplotlib
- pip
- mock
- portalocker
- networkx

- pip:
  - bscearth.utils

