version: "3"

services:
  test-as-postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: autosubmit
      POSTGRES_PASSWORD: autosubmit
      POSTGRES_DB: autosubmit_dev
    ports:
      - "5432:5432"

  test-as-pg-node-1:
    image: pg-as-node-test
    ports:
      - "38000:8000"
      - "38888:8888"
  
  test-as-pg-node-2:
    image: pg-as-node-test
    ports:
      - "38001:8000"
      - "38889:8888"