name: Lint

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
permissions:
  contents: read

jobs:
  ruff-changes-in-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Ruff
        run: pip install ruff
      - name: Run Ruff
        run: ruff check $(git diff --name-only --cached -- '*.py')
